### PR TITLE
FIX problem with extra dimension that makes linear interpolation failing

### PR DESCRIPTION
**Pull request by giovastabile**
Not sure it this is the best fix. In case one is using linear interpolation there is one extra dimension that makes the linear interpolation failing (e.g. one can try tutorial 2 with Linear interpolation). This fix solves the problem

### CODE REVIEW

**Comment by flabowski** [comment]
Do you have a minimal working example of the problem? Not sure if a change in the pod module because of a problem with the linear interpolation module is the best fix.
In case of trouble with linear interpolation in 1D, you might want to consider the [regular_grid module](https://github.com/mathLab/EZyRB/blob/master/ezyrb/regular_grid.py). The 1D linear interpolation used in the [linear module](https://github.com/mathLab/EZyRB/blob/e57fe5106b02bdfa08c5d23ca54cffb690e4401c/ezyrb/linear.py#L44C33-L44C41) is considered legacy (see [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html)).

**Comment by giovastabile** [comment]
`#!/usr/bin/env python
# coding: utf-8

# # EZyRB Tutorial 2
# ## Test several frameworks at once
# 
# In this tutorial, we will explain step by step how to use the **EZyRB** library to test different techniques for building the reduced order model. We will compare different methods of dimensionality reduction, interpolation and accuracy assessment.
# 
# We consider here a computational fluid dynamics problem described by the (incompressible) Navier Stokes equations.
# We will be using the **Navier Stokes Dataset** that contains the output data from a full order flow simulation and can be found on **GitHub** under [Smithers library](https://github.com/mathLab/Smithers).
# **Smithers** is developed by **SISSA mathlab** and it contains some useful datasets and a multi-purpose toolbox that inherits functionality from other packages to make the process of dealing with these datasets much easier with more compact coding.
# 
# The package can be installed using `python -m pip install smithers -U`, but for a detailed description about installation and usage we refer to original [Github page](https://github.com/mathLab/Smithers/blob/master/README.md).
# 
# First of all, we just import the package and instantiate the dataset object.

# In[1]:


from smithers.dataset import NavierStokesDataset
data = NavierStokesDataset()


# The `NavierStokesDataset()` class contains the attribute:
# - `snapshots`: the matrices of snapshots stored by row (one matrix for any output field)
# - `params`: the matrix of corresponding parameters
# - `pts_coordinates`: the coordinates of all nodes of the discretize space
# - `faces`: the actual topology of the discretize space
# - `triang`: the triangulation, useful especially for rendering purposes.
# 
# In the details, `data.snapshots` is a dictionary with the following output of interest:
# - **vx:** velocity in the X-direction. 
# - **vy:** velocity in the Y-direction. 
# - **mag(v):** velocity magnitude.
# - **p:** pressure value.
# 
# In total, the dataset contains 500 parametric configurations in a space of 1639 degrees of freedom. In this case, we have just one parameter, which is the velocity (along $x$) we impose at the inlet.

# In[2]:


for name in ['vx', 'vy', 'p', 'mag(v)']:
    print('Shape of {:7s} snapshots matrix: {}'.format(name, data.snapshots[name].shape))
    
print('Shape of parameters matrix: {}'.format(data.params.shape))


# ### Initial setting
# 
# First of all, we import the required packages.
# 
# From `EZyRB` we need:
# 1. The `ROM` class, which performs the model order reduction process.
# 2. A module such as `Database`, where the matrices of snapshots and parameters are stored. 
# 3. A dimensionality reduction method such as Proper Orthogonal Decomposition `POD` or Auto-Encoder network `AE`.
# 4. An interpolation method to obtain an approximation for the parametric solution for a new set of parameters such as the Radial Basis Function `RBF`, Gaussian Process Regression `GPR`,  K-Neighbors Regressor `KNeighborsRegressor`,  Radius Neighbors Regressor `RadiusNeighborsRegressor` or Multidimensional Linear Interpolator `Linear`.
# 
# We also need to import:
# * `numpy:` to handle arrays and matrices we will be working with.
# * `torch:` to enable the usage of Neural Networks
# * `matplotlib.pyplot:` to handle the plotting environment. 
# * `matplotlib.tri:` for plotting of the triangular grid.

# In[3]:


# Database module
from ezyrb import Database

# Dimensionality reduction methods
from ezyrb import POD, AE

# Approximation/interpolation methods
from ezyrb import RBF, GPR, KNeighborsRegressor, RadiusNeighborsRegressor, Linear, ANN

# Model order reduction calss
from ezyrb import ReducedOrderModel as ROM

import numpy as np
import torch
import torch.nn as nn

import matplotlib.tri as mtri
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore", message="Ill-conditioned matrix ")
get_ipython().run_line_magic('matplotlib', 'inline')


# Before starting with the reduced order model, we visualize some of the snapshots in our dataset.

# In[4]:


fig, ax = plt.subplots(nrows=3, ncols=3, figsize=(16, 8), sharey=True, sharex=True)
ax = ax.flatten()
for i in range(9):
    ax[i].tricontourf(data.triang, data.snapshots['vx'][i], levels=16)
    ax[i].set_title('Original snapshot at inlet velocity = {}'.format(*data.params[i].round(2)))


# In this step, we perform the model order reduction to obtain a reduced space from the full order space. We refer to [Tutorial 1](https://github.com/mathLab/EZyRB/blob/master/tutorials/tutorial-1.ipynb) for the description of the basic workflow, here we just quickly describe the steps implemented in the next cell.
# 
# We start by passing the matrices of the parameters and snapshots to the `Database()` class. It must be said that at this time we create the ROM for the `vx` field. We also instantiate the `POD` and `RBF` object to have a benchmark ROM.

# In[5]:
db = Database(data.params, data.snapshots['vx'])
rom = ROM(db, POD(), Linear())
rom.fit()
rom.predict(20.0)`

**Comment by mtezzele** [comment]
@giovastabile is the problem still there if you use `rom.predict(np.array([20]))` ?

**Comment by mtezzele** [comment]
@ndem0 we should replace `interp1d` with [`np.interp`](https://numpy.org/devdocs/reference/generated/numpy.interp.html#numpy.interp)

**Comment by giovastabile** [comment]
yes because the problem is not in the shape of the parameters but in the shape of the pod modes. The error occurs while doing:

`File [~/.local/lib/python3.10/site-packages/ezyrb/pod.py:124](https://file+.vscode-resource.vscode-cdn.net/home/giova/SISSA/articles_and_presentations/02Submitted/radoncdt_paper/~/.local/lib/python3.10/site-packages/ezyrb/pod.py:124), in POD.inverse_transform(self, X)
    [118](file:///home/giova/.local/lib/python3.10/site-packages/ezyrb/pod.py?line=117) def inverse_transform(self, X):
    [119](file:///home/giova/.local/lib/python3.10/site-packages/ezyrb/pod.py?line=118)     """
    [120](file:///home/giova/.local/lib/python3.10/site-packages/ezyrb/pod.py?line=119)     Projects a reduced to full order solution.
    [121](file:///home/giova/.local/lib/python3.10/site-packages/ezyrb/pod.py?line=120) 
    [122](file:///home/giova/.local/lib/python3.10/site-packages/ezyrb/pod.py?line=121)     :type: numpy.ndarray
    [123](file:///home/giova/.local/lib/python3.10/site-packages/ezyrb/pod.py?line=122)     """
--> [124](file:///home/giova/.local/lib/python3.10/site-packages/ezyrb/pod.py?line=123)     return self.modes.dot(X)

ValueError: shapes (1639,500) and (500,1,1) not aligned: 500 (dim 1) != 1 (dim 1)`

**Comment by giovastabile** [comment]
X should not be 500,1,1 but 500,1

I didn't investigate why this happens only with Linear interpolation

**Comment by mtezzele** [comment]
@giovastabile are you using squeeze? 
If I just use 
`pred = rom.predict(np.array([20]))`
it works with the current version of EZyRB.
Anyway we can not accept this fix because the problem is only in the `Linear` class and this fix breaks other combinations

**Comment by giovastabile** [comment]
Yes, I assume the fix should be in the Linear class. The predict call does not work in case you use a linear interpolation. with RBF everything is fine

**Comment by mtezzele** [comment]
This minimal example works on my machine with the current ezyrb version (even using `predict(20)`):

```
from ezyrb import Database
from ezyrb import POD
from ezyrb import Linear
from ezyrb import ReducedOrderModel as ROM
import numpy as np

db = Database(data.params, data.snapshots['vx'])
rom = ROM(db, POD(), Linear())
rom.fit()
pred = rom.predict(np.array([20]))
print(f'pred = {pred}')
print(f'pred.shape = {pred.shape}')
```

the output is

```
Shape of vx      snapshots matrix: (500, 1639)
Shape of vy      snapshots matrix: (500, 1639)
Shape of p       snapshots matrix: (500, 1639)
Shape of mag(v)  snapshots matrix: (500, 1639)
Shape of parameters matrix: (500, 1)
pred = [2.97702136e-13 4.08038857e-14 5.17295160e-15 ... 4.24164446e+00
 1.03359498e+01 2.86579912e+00]
pred.shape = (1639,)
```

to replicate your error I have to pass `pred = rom.predict(np.array([[20]]))`

**Comment by giovastabile** [comment]
This minimal example does not work in my case:

`from ezyrb import Database
from ezyrb import POD
from ezyrb import Linear
from ezyrb import ReducedOrderModel as ROM
import numpy as np

from smithers.dataset import NavierStokesDataset
data = NavierStokesDataset()

db = Database(data.params, data.snapshots['vx'])
rom = ROM(db, POD(), Linear())
rom.fit()
pred = rom.predict(np.array([20]))
print(f'pred = {pred}')
print(f'pred.shape = {pred.shape}')`

**Comment by ndem0** [comment]
I'm not 100% sure I got the problem: have you tried to run the tests on your machine? The example you provided looks already checked in this test https://github.com/mathLab/EZyRB/blob/e57fe5106b02bdfa08c5d23ca54cffb690e4401c/tests/test_linear.py#L44

**Review by ndem0 — APPROVED** [review]
We were checking the linear interpolation only for 1D input with 1D output, or ND input with ND output. Your case (1D-2D) was never tested before!
Now everything works, I also added a small test to check this behavior in future. Thanks @giovastabile!

**Pull request merged**
